---
title: "Mathematical modelling and phylodynamics for the study of dog rabies dynamics and control: a scoping review"
---

---

## Authors:
Maylis Layan^1,2^, Simon Dellicour^3,4^, Guy Baele^4^, Simon Cauchemez^1^ & Hervé Bourhy^5^

^1^ Mathematical Modelling of Infectious Diseases Unit, Institut Pasteur, UMR2000, CNRS, Paris, France 
<br>
^2^ Sorbonne Université, Paris, France
<br>
^3^ Spatial Epidemiology Lab (SpELL), Université Libre de Bruxelles, Bruxelles, Belgium
<br>
^4^ Department of Microbiology, Immunology and Transplantation, Rega Institute, KU Leuven, Leuven, Belgium 
<br>
^5^ Lyssavirus Epidemiology and Neuropathology Unit, Institut Pasteur, Paris, France
<br>

Full text available [here]().

--- 

## Abstract

**Abstract** Background Rabies is a fatal yet vaccine-preventable disease. In the last two decades, domestic dog populations have been shown to constitute the predominant reservoir of rabies in developing countries, causing 99% of human rabies cases. Despite substantial control efforts, dog rabies is still widely endemic and is spreading across previously rabies-free areas. Developing a detailed understanding of dog rabies dynamics and the impact of vaccination is essential to optimize existing control strategies and developing new ones.

**Objectives** In this scoping review, we aimed at disentangling the respective contributions of mathematical models and phylodynamic approaches to the understanding of rabies dynamics and control in domestic dog populations. We also addressed the methodological limitations of both approaches and the remaining issues related to studying rabies spread and how this could be applied to rabies control.

**Methodology/Principal Findings** We reviewed how mathematical modelling of disease dynamics and phylodynamics have been developed and used to characterize dog rabies dynamics and control. Through a detailed search of the PubMed, Web of Science, and Scopus databases, we identified a total of n = 59 relevant studies using mathematical models (n = 30), phylodynamic inference (n = 22) and interdisciplinary approaches (n = 7). We found that despite often relying on scarce rabies epidemiological data, mathematical models investigated multiple aspects of rabies dynamics and control. These models confirmed the overwhelming efficacy of massive dog vaccination campaigns in all settings and unraveled the role of dog population structure and frequent introductions in dog rabies maintenance. Phylodynamic approaches successfully disentangled the evolutionary and environmental determinants of rabies dispersal and consistently reported support for the role of reintroduction events and human-mediated transportation over long distances in the maintenance of rabies in endemic areas. Potential biases in data collection still need to be properly accounted for in most of these analyses. Finally, interdisciplinary studies were determined to provide the most comprehensive assessments through hypothesis generation and testing. They also represent new avenues, especially concerning the reconstruction of local transmission chains or clusters through data integration.  

**Conclusions** Despite advances in rabies knowledge, substantial uncertainty remains regarding the mechanisms of local spread, the role of wildlife in dog rabies maintenance, and the impact of community behavior on the efficacy of control strategies including vaccination of dogs. Future integrative approaches that use phylodynamic analyses and mechanistic models within a single framework could take full advantage of not only viral sequences but also additional epidemiological information as well as dog ecology data to refine our understanding of rabies spread and control. This would represent a significant improvement on past studies and a promising opportunity for canine rabies research in the frame of the One Health concept that aims to achieve better public health outcomes through cross-sector collaboration.

---

### Author summary

Rabies is a fatal but yet vaccine-preventable zoonotic disease. Domestic dog populations are known to constitute the predominant reservoir of rabies in developing countries, causing 99% of human rabies cases. Despite valuable efforts to control rabies spread, there has been only little no substantial improvement of the global rabies disease burden over the last two decades. Dog rabies is still endemic in Africa, Asia, and the Middle East, in part certainly due to remaining knowledge gaps on dog rabies dynamics. We conducted an in-depth review of the phylodynamic approaches and mathematical models used to study the spread and control of rabies in domestic dogs. We identified 59 relevant studies which used mathematical models (30), phylodynamic approaches (22), or interdisciplinary approaches (7). Our study revealed that these approaches disentangled different aspects of rabies spread and control. Mathematical models support the role of dog population heterogeneity as a key driver of rabies spread, and the overwhelming efficacy of dog vaccination campaigns to control rabies. Phylodynamic studies confirm the role of frequent reintroduction events and human-mediated transportation over long distances in rabies maintenance. Interdisciplinary studies represent a powerful tool to generate and test hypotheses on rabies spread. Finally, we identified new avenues which represent a promising opportunity for canine rabies research to achieve more impactful public health outcomes.

