---
title: "Supplementary Table 1 - General characteristics of the included studies"
output: html_document
---

Supplementary Table 1 is also available in Excel format [here]("https://github.com/mlayan/RabiesScopingReview/blob/gh-pages/supplementary/S1_Table.xlsx").

Colors refer to the type of study:

* <span style="color: gold;">Phylodynamics</span>
* <span style="color: indianred;">Mathematical modelling</span>
* <span style="color: darkorange;">Interdisciplinary study</span>

In phylodynamic studies, the `Temporal scale` column corresponds to the sampling window of rabies virus genetic sequences. 


```{r setup, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results=FALSE}
library(readxl)
library(dplyr)
library(kableExtra)
library(XML)
library(tibble)

## Read excel table
dt = read_excel("supplementary/S1_Table.xlsx", sheet = "ST1", skip = 2)

## Rename file to ZIP
myZipFile <- sub("xlsx", "zip", "supplementary/S1_Table.xlsx")
file.copy(from = "supplementary/S1_Table.xlsx", to = myZipFile, overwrite = T)

# unzip the file
unzip(myZipFile)

# unzipping produces a bunch of files which we can read using the XML package
# assume sheet1 has our data
file.remove("supplementary/S1_Table.zip")
xml_ref <- xmlParse("xl/worksheets/sheet1.xml")
xml_url <- xmlParse("xl/worksheets/_rels/sheet1.xml.rels")

# Extract data
url_tab = data.frame(
  url = as.character( xpathApply(xml_url, "//x:Relationship/@Target", namespaces = "x")),
  id = as.character( xpathApply(xml_url, "//x:Relationship/@Id", namespaces = "x"))
)

hyperlinks = xpathApply(xml_ref, "//x:hyperlinks/x:hyperlink", xmlAttrs, namespaces = "x")
ref_tab = data.frame(t(sapply(hyperlinks, function(x) x[c("ref", "id")])))

# Merge data bases
hyp = dplyr::right_join(ref_tab, url_tab) %>%
  dplyr::filter(!is.na(ref)) %>%
  dplyr::mutate(ref = as.numeric(gsub("^G", "", ref))) %>%
  dplyr::arrange(ref) %>%
  cbind(text = dt$Reference[-c(60,61)]) %>%
  dplyr::mutate(new_value = paste("<a href=\"", url, "\">", text, "</a>", sep = ""))


## Create table
to_display = dt[-c(60,61), -c(8,9)] %>%
  dplyr::mutate(`Temporal scale` = ifelse(`Temporal scale` == "-", "", `Temporal scale`),
         `Additionnal host species` = ifelse(`Additionnal host species` == "-", "", `Additionnal host species`))

# Replace windows linebreaks
for (COL in colnames(to_display)) {
 to_display[[COL]] <- stringr::str_replace_all(to_display[[COL]], "\\r\\n", "<br>") 
}

# Add subscripts
to_display$`Study area`[to_display$`Study area` == "Nonea"] = "None<sup>a</sup>"

# Add references in hyperlinks
to_display$Reference = hyp$new_value
```


```{r table, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
# Display table with hyperlinks
kable(to_display, format = "html", escape = F) %>%
  kable_styling() %>%
  row_spec(0, color = "black", bold = T, extra_css = 'vertical-align: middle !important;') %>%
  row_spec(1:22, color = "black", background = "gold") %>% #"#EEDD82"
  row_spec(23:52, color = "black", background = "indianred") %>% #EE2C2C"
  row_spec(53:59, color = "black", background = "darkorange") %>% #EE9A49"
  footnote(alphabet = gsub("^a", "", dt$`#`[61])) %>%
  kableExtra::scroll_box(width = "100%", height = "800px")
```


