---
title: "Supplementary Table 5 - Estimated parameters in phylodynamic studies"
output: html_document
---

Supplementary Table 5 is also available in Excel format [here](https://github.com/mlayan/RabiesScopingReview/blob/gh-pages/supplementary/S5_Table.xlsx).

```{r setup, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results=FALSE}
library(readxl)
library(dplyr)
library(kableExtra)
library(XML)
library(tibble)

## Read excel table
dt = read_excel("supplementary/S5_Table.xlsx", sheet = "ST5", skip = 2)

## Rename file to ZIP
myZipFile <- sub("xlsx", "zip", "supplementary/S5_Table.xlsx")
file.copy(from = "supplementary/S5_Table.xlsx", to = myZipFile, overwrite = T)

# unzip the file
unzip(myZipFile)

# unzipping produces a bunch of files which we can read using the XML package
# assume sheet1 has our data
file.remove("supplementary/S5_Table.zip")
xml_ref <- xmlParse("xl/worksheets/sheet1.xml")
xml_url <- xmlParse("xl/worksheets/_rels/sheet1.xml.rels")

# Extract data
url_tab = data.frame(
  url = as.character( xpathApply(xml_url, "//x:Relationship/@Target", namespaces = "x")),
  id = as.character( xpathApply(xml_url, "//x:Relationship/@Id", namespaces = "x"))
)

hyperlinks = xpathApply(xml_ref, "//x:hyperlinks/x:hyperlink", xmlAttrs, namespaces = "x")
ref_tab = data.frame(t(sapply(hyperlinks, function(x) x[c("ref", "id")])))

# Merge data bases
hyp = dplyr::right_join(ref_tab, url_tab) %>%
  dplyr::filter(!is.na(ref)) %>%
  dplyr::mutate(ref = as.numeric(gsub("^I", "", ref))) %>%
  dplyr::arrange(ref) %>%
  dplyr::filter(!is.na(ref)) %>%
  cbind(text = dt$Reference[-c(20:25)]) %>%
  dplyr::mutate(new_value = paste("<a href=\"", url, "\">", text, "</a>", sep = ""))


## Create table
to_display = dt[-c(20:25), 1:9]

# Replace windows linebreaks
for (COL in colnames(to_display)) {
 to_display[[COL]] <- stringr::str_replace_all(to_display[[COL]], "\\r\\n", "<br>") 
}

# Add references in hyperlinks
to_display$Reference = hyp$new_value

# Superscripts and subscripts
for (l in c("a", "b", "c", "d")) {
  to_display[] <- lapply(to_display, function(x) gsub(paste0(l, "$"), paste0("<sup>", l, "</sup>"), x))
  to_display[] <- lapply(to_display, function(x) gsub(paste0(l, "<br>"), paste0("<sup>", l, "</sup><br>"), x))
}

for (l in c("weighted", "Great circle distances", "Overall", "Road distances", "wavefront", "Dogs", "Cerdocyon thous")) {
  to_display[] <- lapply(to_display, function(x) gsub(l, paste0("<sub>", l, "</sub>"), x))
}

colnames(to_display) = gsub("-1", "<sup>-1</sup>", colnames(to_display))
colnames(to_display) = gsub("2", "<sup>2</sup>", colnames(to_display))
  
# Remove dashes
to_display[] <- lapply(to_display, function(x) gsub("^-$", "", x))

```

```{r tabl, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
kbl(to_display, format = "html", escape = F) %>%
  kable_styling() %>%
  row_spec(0, color = "black", bold = T, extra_css = 'vertical-align: middle !important;') %>%
  row_spec(1:19, color = "black") %>%
  footnote(general = dt$`Viral lineages`[25], 
           alphabet = gsub("^[a-z] ", "", dt$`Viral lineages`[21:24])) %>%
  kableExtra::scroll_box(width = "100%", height = "800px")

```


