---
title: "Supplementary Table 6 - Estimated parameters in mathematical models"
output: html_document
---

Supplementary Table 6 is also available in Excel format <a href="https://github.com/mlayan/RabiesScopingReview/blob/gh-pages/supplementary/S6_Table.xlsx">here</a>.

```{r setup, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results=FALSE}
library(readxl)
library(dplyr)
library(kableExtra)
library(XML)
library(tibble)

## Read excel table
dt = read_excel("supplementary/S6_Table.xlsx", sheet = "ST6", skip = 2)

## Rename file to ZIP
myZipFile <- sub("xlsx", "zip", "supplementary/S6_Table.xlsx")
file.copy(from = "supplementary/S6_Table.xlsx", to = myZipFile, overwrite = T)

# unzip the file
unzip(myZipFile)

# unzipping produces a bunch of files which we can read using the XML package
# assume sheet1 has our data
file.remove("supplementary/S6_Table.zip")
xml_ref <- xmlParse("xl/worksheets/sheet1.xml")
xml_url <- xmlParse("xl/worksheets/_rels/sheet1.xml.rels")

# Extract data
url_tab = data.frame(
  url = as.character( xpathApply(xml_url, "//x:Relationship/@Target", namespaces = "x")),
  id = as.character( xpathApply(xml_url, "//x:Relationship/@Id", namespaces = "x"))
)

hyperlinks = xpathApply(xml_ref, "//x:hyperlinks/x:hyperlink", xmlAttrs, namespaces = "x")
ref_tab = data.frame(t(sapply(hyperlinks, function(x) x[c("ref", "id")])))

# Merge data bases
hyp = dplyr::right_join(ref_tab, url_tab) %>%
  dplyr::filter(!is.na(ref)) %>%
  dplyr::mutate(ref = as.numeric(gsub("^H", "", ref))) %>%
  dplyr::arrange(ref) %>%
  dplyr::filter(!is.na(ref)) %>%
  cbind(text = dt$Reference[-c(27:30)]) %>%
  dplyr::mutate(new_value = paste("<a href=\"", url, "\">", text, "</a>", sep = ""))


## Create table
to_display = dt[-c(27:30), ]

# Replace windows linebreaks
for (COL in colnames(to_display)) {
 to_display[[COL]] <- stringr::str_replace_all(to_display[[COL]], "\\r\\n", "<br>") 
}

# Add references in hyperlinks
to_display$Reference = hyp$new_value

# Superscripts
to_display$`Reproduction ratio` = gsub("a$", "<sup>a</sup>", to_display$`Reproduction ratio`)
to_display$`Reproduction ratio` = gsub("b$", "<sup>b</sup>", to_display$`Reproduction ratio`)
to_display$`Reproduction ratio` = gsub("b<br>", "<sup>b</sup><br>", to_display$`Reproduction ratio`)

# Change units
to_display[] <- lapply(to_display, function(x) gsub("km2", "km<sup>2</sup>", x))
to_display[] <- lapply(to_display, function(x) gsub("km-2", "km<sup>-2</sup>", x))
to_display[] <- lapply(to_display, function(x) gsub("dogs-1", "dogs<sup>-1</sup>", x))
to_display[] <- lapply(to_display, function(x) gsub("week-1", "week<sup>-1</sup>", x))
to_display[] <- lapply(to_display, function(x) gsub("day-1", "day<sup>-1</sup>", x))

# Remove dashes
to_display[] <- lapply(to_display, function(x) gsub("^-$", "", x))

```

```{r table, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
kbl(to_display, format = "html", escape = F) %>%
  kable_styling() %>%
  row_spec(0, color = "black", bold = T, extra_css = 'vertical-align: middle !important;') %>%
  row_spec(1:26, color = "black") %>%
  footnote(general = dt$Location[30], 
           alphabet = gsub("^[a-z] ", "", dt$Location[28:29])) %>%
  kableExtra::scroll_box(width = "100%", height = "800px")

```


```{r delete, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results=FALSE}
file.remove("[Content_Types].xml")
unlink("_rels", recursive = TRUE)
unlink("xl", recursive = TRUE)
unlink("docProps", recursive = TRUE)

```
